/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#121318",
        "surface-dim": "#121318",
        "surface-bright": "#38393f",
        "surface-container-lowest": "#0d0e13",
        "surface-container-low": "#1a1b21",
        "surface-container": "#1e1f25",
        "surface-container-high": "#292a2f",
        "surface-container-highest": "#34343a",
        "on-surface": "#e3e1e9",
        "on-surface-variant": "#d8c3ad",
        "inverse-surface": "#e3e1e9",
        "inverse-on-surface": "#2f3036",
        "outline": "#a08e7a",
        "outline-variant": "#534434",
        "surface-tint": "#ffb95f",
        "primary": "#ffc174",
        "on-primary": "#472a00",
        "primary-container": "#f59e0b",
        "on-primary-container": "#613b00",
        "inverse-primary": "#855300",
        "secondary": "#dec48b",
        "on-secondary": "#3e2e03",
        "secondary-container": "#59471a",
        "on-secondary-container": "#cfb67e",
        "tertiary": "#ffc08e",
        "on-tertiary": "#4d2600",
        "tertiary-container": "#ff9837",
        "on-tertiary-container": "#6a3700",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffddb8",
        "primary-fixed-dim": "#ffb95f",
        "on-primary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#653e00",
        "secondary-fixed": "#fbdfa5",
        "secondary-fixed-dim": "#dec48b",
        "on-secondary-fixed": "#251a00",
        "on-secondary-fixed-variant": "#564418",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "background": "#121318",
        "on-background": "#e3e1e9",
        "surface-variant": "#34343a"
      },
      fontFamily: {
        "display-hero": ["Syne", "sans-serif"],
        "display-hero-mobile": ["Syne", "sans-serif"],
        "headline-xl": ["Syne", "sans-serif"],
        "headline-xl-mobile": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "label-mono-sm": ["JetBrains Mono", "monospace"],
        "label-mono-xs": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-hero": ["84px", { lineHeight: "90px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-hero-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-xl": ["56px", { lineHeight: "62px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-mono-xs": ["9px", { lineHeight: "12px", letterSpacing: "0.14em", fontWeight: "600" }]
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.25rem",
        "gutter-desktop": "1.75rem",
        "margin": "1.25rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "4rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem"
      }
    },
  },
  plugins: [],
}
